### ISSUE TITLE
Homebrew formula uses deprecated API

### ISSUE THREAD

**Issue by abasson-vmware** [vmware-tanzu-labs/git-story#2]
Running `brew doctor` surfaces the following warning:

> Warning: Calling bottle :unneeded is deprecated! There is no replacement.
> Please report this issue to the git-story-branch/tap tap (not Homebrew/brew or Homebrew/core):
>   /usr/local/Homebrew/Library/Taps/git-story-branch/homebrew-tap/git-story.rb:11

**Comment by carpeliam** [comment]
Thanks Alex for raising! The repo for the homebrew formula is over at https://github.com/git-story-branch/homebrew-tap. Closing this in favor of an earlier PR, https://github.com/git-story-branch/homebrew-tap/pull/1.
